#!/usr/bin/env bash
set -eu

grey(){ echo -e "\e[0;30m${@}\e[0;30m" ; }
green(){ echo -e "\e[0;32m${@}\e[0;30m" ; }
blue(){ echo -e "\e[0;34m${@}\e[0;30m" ; }

blue "setup weblate remote"
git remote show weblate > /dev/null || git remote add weblate https://weblate.framasoft.org/git/inventaire/server/

blue "pull weblate commits"
git pull weblate master

blue "fetch wikidata translations"
./scripts/fetch/fetch_wikidata_translations

green "done fetching"
